#index:
#    path: /
#    controller: App\Controller\DefaultController::index

ajax_search:
    path: /search
    controller: App\Controller\ArtController::search


list_article:
    path: /AllArticle
    controller: App\Controller\ArtController::getArticle
    methods: GET

list_artic:
    path: /addarticle/new
    controller: App\Controller\ArtController::addarticle
    methods: GET
    
list_articles:
    path: /updatearticle/{"id"}
    controller: App\Controller\ArtController::updatearticle
    methods: GET

list_articless:
    path: DelArticle/{id}
    controller: App\Controller\ArtController::DelArticle

