package com.mycompany.myapp;




import Form.AjoutBoutiqueForm;
import Form.AjoutProduitForm;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import userclasses.StateMachine;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {
   
    private Form current;
    private Resources theme;
    

    public void init(Object context) {
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

public void start() {
    AjoutProduitForm produitForm = new AjoutProduitForm();
  
    
    // Afficher les deux formulaires
    produitForm.show();
  
    
}
    public void stop() {
     
        }
    
    
    public void destroy() {
    }
}
