package com.mycompany.myapp;

import com.codename1.io.Log;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import com.codename1.ui.list.DefaultListModel;
import entity.artist;
import java.util.ArrayList;
import java.util.HashMap;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {
    DefaultListModel<HashMap<String, Object>> model = new DefaultListModel<>();
    private Form current;
    private Resources theme;
    

    public void init(Object context) {
        
        Toolbar.setGlobalToolbar(true);
        theme = UIManager.initFirstTheme("/theme");
        
        
         // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }

    public void start() {    
        if(current != null){
            current.show();
            return;
        }
        Menu m = new Menu(theme);
        m.show();
       
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
